---
author: "Fernando Mateos-González"
date: Last update "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    code_download: true
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
      df_print: paged
  md_document:
    variant: markdown_github
  pdf_document:
    toc: yes
title: "Work sheets"


# title: "Work sheets"
# author: "Fernando Mateos-González"
# date: "`r format(Sys.time(), '%d %B, %Y')`"
# output:
#   word_document:
#     toc: no
#     fig_caption: true
#     reference_docx: styleword.docx
# 
#   

knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "output") })
  
---

```{r global_options, echo=FALSE}
# knitr::opts_chunk$set(fig.width=6, fig.asp = 0.618, fig.path='output/figs/',
#                       echo=TRUE, warning=FALSE, message=FALSE, cache= FALSE)


options(allow_html_in_all_outputs=TRUE)
```


# Library

```{r library, message=FALSE, warning=FALSE}
# install.packages("pacman")
# writeLines(pacman::p_lib(), "~/Desktop/list_of_R_packages.csv") # to quickly back up packages
# remotes::install_github("ThinkR-open/remedy")


pacman::p_load(tidyverse,janitor, data.table, here, rio, lubridate,writexl,
               gtsummary,  #to make tables
               flextable,  #to save tables in word
               clockify   #API to get data
)


```

# Data google sheets

```{r}

# googledrive::drive_download("worksheet", type ="csv", here("data", "worksheet.csv"))


worksheet <- googledrive::drive_get("worksheet") %>% 
  googlesheets4::read_sheet() %>% 
  dplyr::mutate(month = lubridate::month(date, label = T)) %>% 
  dplyr::mutate(day = lubridate::day(date)) %>% 
  dplyr::mutate(year = lubridate::year(date)) %>% 
  dplyr::mutate(time = as.numeric(time))


by_date <- worksheet %>% 
  dplyr::filter(month =="Jan") %>% 
  dplyr::group_by(date) %>% 
  dplyr::mutate(time = sum(time)) %>% 
  dplyr::mutate(tasks_day = paste0(task,collapse = ", ")) %>% 
  dplyr::select(year, day, month, tasks_day,time, date) %>% 
  dplyr::distinct() %>% 
  dplyr::ungroup() %>% 
  dplyr::select(!date)



 # nando_timesheet <- googlesheets4::gs4_create(
 #    "nando_timesheet",
 #    sheets = "January")
  
 googlesheets4::sheet_write(by_date, ss = nando_timesheet, sheet = "January")
 
   


```

# Data clockify

```{r}

source(here::here("api.R"))

set_api_key(clock_keys)

projects <- clockify::projects()

data_clock<- clockify::time_entries(concise = F) 



```

